on:
  push:
    branches: [release/*]

jobs:
  pr:
    env:
      GH_TOKEN: ${{ github.token }}

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: list-open
        run: gh pr list
          --base ${{ github.event.repository.default_branch }}
          --head ${{ github.ref_name }}
          --state open
          --json number
          --jq '.[].number' | xargs printf 'prs=%s\n' >>$GITHUB_OUTPUT

      - if: steps.list-open.outputs.prs == ''
        run: 'gh pr create
          --base ${{ github.event.repository.default_branch }}
          --head ${{ github.ref_name }}
          --assignee ${{ github.actor }}
          --label chore
          --title "chore(back-merge): ${{ github.ref_name }}"
          --fill-verbose'
