name: `test markdown`

on:
  workflow_dispatch:

env:
  GIT_SSH_COMMAND: ssh -i deploy_key

jobs:
  commit-and-push:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config --global user.name 'gitHub-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git remote set-url origin git@github.com:${{ github.repository }}.git

          cat <<EOF >./deploy_key
          ${{ secrets.DEPLOY_PRIVATE_KEY }}
          EOF

          chmod 600 ./deploy_key

      - name: commit and push changes
        run: |
          git commit --allow-empty -m "dummy commit"
          git push origin
