on:
  push:
  workflow_dispatch:

jobs:
  clone:
    outputs:
      all: ${{ toJSON(steps.all.outputs) }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/config-ninja
          path: .local/config-ninja

      - run: ls .local/config-ninja

      - id: all
        run: |
          { echo a=0; echo b=1; echo c=2; echo d-e=3-4; } >>"$GITHUB_OUTPUT"

  print:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Convert outputs to JSON and print
        run: |
          cat <<'EOF' >>"$GITHUB_STEP_SUMMARY"
          ```json
          ${{ needs.clone.outputs.all }}
          ```
          EOF

  json:
    env:
      JSON_DATA: >
        {
          "a": 0,
          "b": 1,
          "c": 2
        }
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "$JSON_DATA" | jq .
