on:
  push:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/config-ninja
          path: .local/config-ninja

      - run: ls .local/config-ninja
